tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: services_short_description
            field:
              antlers: false
              type: textarea
              display: 'Short Description'
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: services_background_color
            field:
              swatches:
                - '#48CDA0'
                - '#ED5F38'
                - '#007EFF'
                - '#E6BC13'
                - '#ED38D1'
                - '#A348CD'
              allow_any: true
              type: color
              display: 'Background Color'
              icon: color
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: services_image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Image
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              validate:
                - image
          -
            handle: ser_content
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Content
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
  seo:
    display: SEO
    sections:
      -
        display: 'New Section'
        fields:
          -
            import: seo
title: Service
